sudo: false
language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - env: MPI_IMPL=openmpi BUILD_SYSTEM=cmake
    - env: MPI_IMPL=openmpi BUILD_SYSTEM=autotools
env:
  - MPI_IMPL=mpich   BUILD_SYSTEM=cmake
  - MPI_IMPL=mpich   BUILD_SYSTEM=autotools
  - MPI_IMPL=openmpi BUILD_SYSTEM=cmake
  - MPI_IMPL=openmpi BUILD_SYSTEM=autotools
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir -p $TRAVIS_ROOT
  - export PATH=$TRAVIS_ROOT/bin:$PATH
install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL $BUILD_SYSTEM
script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL $BUILD_SYSTEM
after_failure:
  - find . -name config.log -exec grep -L "configure: exit 0" {} ";" | xargs cat
