language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  - sh ./travis/dep-$TRAVIS_OS_NAME.sh $MPI_IMPL
script:
  - sh ./travis/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./config.log
