language: c
os: linux
compiler:
  - gcc
  - clang
env:
  - RUN_TEST=buildonly
  - RUN_TEST=check
#notifications:
#  email:
#    recipients:
#      - jeff.science@gmail.com
#    on_success: change
#    on_failure: always
before_install: ./travis/dep-$TRAVIS_OS_NAME.sh
script: ./travis/build-$TRAVIS_OS_NAME.sh
after_failure: cat ./config.log
